# Generated by Django 4.0.1 on 2022-03-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('primary_phone', models.IntegerField()),
                ('secondary_phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
