# Generated by Django 4.0.3 on 2022-04-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_instructordocuments_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructordocuments',
            name='instructor',
        ),
        migrations.AddField(
            model_name='instructordocuments',
            name='instructor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.instructor', unique=True),
        ),
    ]
