# Generated by Django 4.0.1 on 2022-03-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_created_at_instructor_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=255)),
                ('criminal', models.CharField(max_length=255)),
                ('curriculum', models.CharField(max_length=255)),
                ('interview_quests', models.CharField(max_length=255)),
                ('exams', models.CharField(max_length=255)),
                ('tests', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.instructor')),
            ],
        ),
    ]
