# Generated by Django 4.0.3 on 2022-04-21 21:20

from django.db import migrations, models
import instructor.models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_instructor_cpf_alter_instructor_primary_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructordocuments',
            name='scholar_history',
            field=models.FileField(null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='criminal',
            field=models.FileField(null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='curriculum',
            field=models.FileField(null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='exams',
            field=models.FileField(null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='identity',
            field=models.FileField(null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='interview_quests',
            field=models.FileField(null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='residence',
            field=models.FileField(null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='tests',
            field=models.FileField(null=True, upload_to=instructor.models.user_directory_path),
        ),
    ]
