# Generated by Django 4.0.3 on 2022-04-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_remove_instructordocuments_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructordocuments',
            name='instructor_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.instructor'),
        ),
    ]
