# Generated by Django 4.0.3 on 2022-04-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_alter_instructordocuments_instructor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructordocuments',
            old_name='instructor_id',
            new_name='instructor',
        ),
    ]
