# Generated by Django 4.0.3 on 2022-04-21 22:53

from django.db import migrations, models
import instructor.models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_rename_instructor_id_instructordocuments_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructordocuments',
            name='criminal',
            field=models.FileField(blank=True, null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='exams',
            field=models.FileField(blank=True, null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='interview_quests',
            field=models.FileField(blank=True, null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='residence',
            field=models.FileField(blank=True, null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='scholar_history',
            field=models.FileField(blank=True, null=True, upload_to=instructor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='instructordocuments',
            name='tests',
            field=models.FileField(blank=True, null=True, upload_to=instructor.models.user_directory_path),
        ),
    ]
