# Generated by Django 4.0.3 on 2022-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_alter_instructordocuments_criminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='ready_documents',
            field=models.BooleanField(default=False),
        ),
    ]
