# Generated by Django 4.0.3 on 2022-05-19 01:15

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('primary_phone', models.CharField(max_length=100)),
                ('secondary_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateTimeField()),
                ('cpf', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('issuing_agency', models.CharField(choices=[('SSP', 'SSP - Secretaria de Segurança Pública'), ('PM', 'PM - Polícia Militar'), ('PC', 'PC - Policia Civil'), ('CNT', 'CNT - Carteira Nacional de Habilitação'), ('DIC', 'DIC - Diretoria de Identificação Civil'), ('CTPS', 'CTPS - Carteira de Trabaho e Previdência Social'), ('FGTS', 'FGTS - Fundo de Garantia do Tempo de Serviço'), ('IFP', 'IFP - Instituto Félix Pacheco'), ('IPF', 'IPF - Instituto Pereira Faustino'), ('IML', 'IML - Instituto Médico-Legal'), ('MTE', 'MTE - Ministério do Trabalho e Emprego'), ('MMA', 'MMA - Ministério da Marinha'), ('MAE', 'MAE - Ministério da Aeronáutica'), ('MEX', 'MEX - Ministério do Exército'), ('POF', 'POF - Polícia Federal'), ('POM', 'POM - Polícia Militar'), ('SES', 'SES - Carteira de Estrangeiro'), ('SJS', 'SJS - Secretaria da Justiça e Segurança'), ('SJTS', 'SJTS - Secretaria da Justiça do Trabalho e Segurança'), ('ZZZ', 'ZZZ - Outros (inclusive exterior)')], max_length=100)),
                ('scholarity', models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental completo'), ('Ensino Medio', 'Ensino Medio completo'), ('Ensino Superior', 'Ensino Superior completo'), ('Pos Graduacao', 'Pós-Graduação completo')], max_length=100)),
                ('working_company_name', models.CharField(max_length=100)),
                ('naturalness', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('avsec_work', models.CharField(blank=True, max_length=100, null=True)),
                ('aviation_work', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('neigh', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=255)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('ready_documents', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='class.classes')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('identity', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('cnh', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('criminal', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('distribution_criminal', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('basic_avsec_certificate', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('cnv', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('pilot_license', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('forwarding_in_service', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('work_card', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('avsec_certificate', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('certified_high_school', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('identity', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('cnh', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('criminal', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('distribution_criminal', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('basic_avsec_certificate', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('cnv', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('pilot_license', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('forwarding_in_service', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('work_card', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('avsec_certificate', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('certified_high_school', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('proof_of_address', models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form_observation', models.TextField(blank=True, null=True)),
                ('identity_observation', models.TextField(blank=True, null=True)),
                ('cnh_observation', models.TextField(blank=True, null=True)),
                ('criminal_observation', models.TextField(blank=True, null=True)),
                ('distribution_criminal_observation', models.TextField(blank=True, null=True)),
                ('basic_avsec_certificate_observation', models.TextField(blank=True, null=True)),
                ('cnv_observation', models.TextField(blank=True, null=True)),
                ('pilot_license_observation', models.TextField(blank=True, null=True)),
                ('forwarding_in_service_observation', models.TextField(blank=True, null=True)),
                ('work_card_observation', models.TextField(blank=True, null=True)),
                ('avsec_certificate_observation', models.TextField(blank=True, null=True)),
                ('certified_high_school_observation', models.TextField(blank=True, null=True)),
                ('proof_of_address_observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
    ]
