# Generated by Django 4.0.3 on 2022-05-19 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_classesname_remove_classes_name_classes_name_class'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='class.classesname'),
        ),
    ]
