# Generated by Django 4.0.3 on 2022-04-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_password_alter_student_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocuments',
            name='criminal_record',
        ),
    ]
