# Generated by Django 4.0.3 on 2022-04-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_documentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentstatus',
            name='student',
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='documents',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentdocuments'),
        ),
        migrations.CreateModel(
            name='DocumentObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('identity_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('criminal_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('basic_avsec_certificate_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('cnv_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('pilot_license_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('forwarding_in_service_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('work_card_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('avsec_certificate_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('certified_high_school_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('proof_of_address_observation', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.documentstatus')),
            ],
        ),
    ]
