# Generated by Django 4.0.3 on 2022-04-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_documentstatus_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentobservation',
            name='avsec_certificate_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='basic_avsec_certificate_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='certified_high_school_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='cnv_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='criminal_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='forwarding_in_service_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='identity_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='pilot_license_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='proof_of_address_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='registration_form_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='work_card_observation',
            field=models.TextField(blank=True, default='PENDENTE', null=True),
        ),
    ]
