# Generated by Django 4.0.3 on 2022-04-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_documentobservation_avsec_certificate_observation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentobservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='documentstatus',
            name='documents',
        ),
        migrations.AddField(
            model_name='documentobservation',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
