# Generated by Django 4.0.3 on 2022-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_documentobservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentobservation',
            name='avsec_certificate_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='basic_avsec_certificate_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='certified_high_school_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='cnv_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='criminal_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='forwarding_in_service_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='identity_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='pilot_license_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='proof_of_address_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='registration_form_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentobservation',
            name='work_card_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='avsec_certificate',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='basic_avsec_certificate',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='certified_high_school',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='cnv',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='criminal',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='forwarding_in_service',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='identity',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='pilot_license',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='proof_of_address',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='registration_form',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='work_card',
            field=models.CharField(choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100),
        ),
    ]
