# Generated by Django 4.0.3 on 2022-05-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_documentobservation_avsec_certificate_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ready_documents',
            field=models.BooleanField(default=False),
        ),
    ]
