# Generated by Django 4.0.3 on 2022-05-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_ready_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstatus',
            name='avsec_certificate',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='basic_avsec_certificate',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='certified_high_school',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='cnv',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='criminal',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='forwarding_in_service',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='identity',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='pilot_license',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='proof_of_address',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='registration_form',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='work_card',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
    ]
