# Generated by Django 4.0.3 on 2022-05-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_documentstatus_avsec_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentobservation',
            old_name='avsec_certificate_observation',
            new_name='avsec_certificate',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='basic_avsec_certificate_observation',
            new_name='basic_avsec_certificate',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='certified_high_school_observation',
            new_name='certified_high_school',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='cnv_observation',
            new_name='cnv',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='criminal_observation',
            new_name='criminal',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='forwarding_in_service_observation',
            new_name='forwarding_in_service',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='identity_observation',
            new_name='identity',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='proof_of_address_observation',
            new_name='pilot_license',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='pilot_license_observation',
            new_name='proof_of_address',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='registration_form_observation',
            new_name='registration_form',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='work_card_observation',
            new_name='work_card',
        ),
    ]
