# Generated by Django 4.0.3 on 2022-05-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_rename_avsec_certificate_observation_documentobservation_avsec_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentobservation',
            old_name='avsec_certificate',
            new_name='avsec_certificate_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='basic_avsec_certificate',
            new_name='basic_avsec_certificate_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='certified_high_school',
            new_name='certified_high_school_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='cnv',
            new_name='cnv_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='criminal',
            new_name='criminal_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='forwarding_in_service',
            new_name='forwarding_in_service_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='identity',
            new_name='identity_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='pilot_license',
            new_name='pilot_license_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='proof_of_address',
            new_name='proof_of_address_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='registration_form',
            new_name='registration_form_observation',
        ),
        migrations.RenameField(
            model_name='documentobservation',
            old_name='work_card',
            new_name='work_card_observation',
        ),
    ]
