# Generated by Django 4.0.3 on 2022-05-18 03:56

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_documentobservation_cnh_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobservation',
            name='distribution_criminal_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='distribution_criminal',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento recusado')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='distribution_criminal',
            field=models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path),
        ),
    ]
