# Generated by Django 4.0.3 on 2022-05-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_documentobservation_distribution_criminal_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='avsec_certificate',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='basic_avsec_certificate',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='certified_high_school',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='cnh',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='cnv',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='criminal',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='distribution_criminal',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='forwarding_in_service',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='identity',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='pilot_license',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='proof_of_address',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='registration_form',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='work_card',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Documento aprovado'), ('PENDENTE', 'Aguardando aprovação'), ('RECUSADO', 'Documento não aceito')], default='PENDENTE', max_length=100, null=True),
        ),
    ]
