# Generated by Django 4.0.3 on 2022-05-19 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anac_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('neigh', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('MANHA/TARDE', 'Manhã/Tarde'), ('TARDE/NOITE', 'Tarde/Noite'), ('MANHA/TARDE/NOITE', 'Manhã/Tarde/Noite'), ('MANHA/NOITE', 'Manhã/Noite')], max_length=255, null=True)),
                ('initial_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.instructor')),
            ],
        ),
    ]
