# Generated by Django 4.0.3 on 2022-05-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='period',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('MANHA/TARDE', 'Manhã/Tarde'), ('TARDE/NOITE', 'Tarde/Noite'), ('MANHA/TARDE/NOITE', 'Manhã/Tarde/Noite'), ('MANHA/NOITE', 'Manhã/Noite')], max_length=255, null=True),
        ),
    ]
