# Generated by Django 4.0.3 on 2022-05-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_classesname_remove_classes_name_classes_name_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='workload',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
