# Generated by Django 4.0.3 on 2022-03-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_alter_class_number_alter_class_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
