# Generated by Django 4.0.3 on 2022-03-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_alter_class_number_alter_class_zipcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
    ]
