# Generated by Django 4.0.1 on 2022-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0006_classes_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='anac_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
